### ISSUE TITLE
Bug: recruitment impossible

### ISSUE THREAD

**Issue by f851374a** [dninemfive/psychologyimprisonmentpatch#1]
Well... i had an issue here. When successful recruitment attempt happens, recruitment is not happening. More strangely, prisoners starts to hate my faction, kinda reversed effects :D.
I captured this moment in debug mode and got an debug report, i hope it will help.

---

JobDriver threw exception in initAction for pawn Whistler driver=JobDriver_ChatWithPrisoner (toilIndex=19) driver.job=(PrisonerAttemptRecruit (Job_118037) A=Thing_Human58578) lastJobGiver=RimWorld.JobGiver_Work
System.TypeLoadException: Could not load type 'Psychology.ThoughtDefOfPsychology' from assembly 'PsychologyImprisonmentPatch'.
at (wrapper dynamic-method) RimWorld.InteractionWorker_RecruitAttempt.DoRecruit_Patch2 (Verse.Pawn,Verse.Pawn,single,string&,string&,bool,bool) <0x00036>
at RimWorld.InteractionWorker_RecruitAttempt.Interacted (Verse.Pawn,Verse.Pawn,System.Collections.Generic.List`1<Verse.RulePackDef>,string&,string&,Verse.LetterDef&) <0x009d2>
at RimWorld.Pawn_InteractionsTracker.TryInteractWith (Verse.Pawn,RimWorld.InteractionDef) <0x0039b>
at RimWorld.Toils_Interpersonal/<TryRecruit>c__AnonStorey5.<>m__0 () <0x000d6>
at Verse.AI.JobDriver.TryActuallyStartNextToil () <0x0043a>

Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
RimWorld.<GotoInteractablePosition>c__AnonStorey0:<>m__0()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Notify_PatherArrived()
Verse.AI.Pawn_PathFollower:PatherArrived()
Verse.AI.Pawn_PathFollower:StartPath(LocalTargetInfo, PathEndMode)
RimWorld.<GotoPrisoner>c__AnonStorey1:<>m__0()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:DriverTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick_Patch1(Object)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Comment by dninemfive** [comment]
I seem to have lost track of this issue at the time, and I'm no longer maintaining this mod. Sorry 'bout that.
